<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit26b032b6ee3ef105786461d5ba3f6e85
{
    public static $prefixesPsr0 = array (
        'O' => 
        array (
            'OAuth\\Unit' => 
            array (
                0 => __DIR__ . '/..' . '/lusitanian/oauth/tests',
            ),
            'OAuth' => 
            array (
                0 => __DIR__ . '/..' . '/lusitanian/oauth/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit26b032b6ee3ef105786461d5ba3f6e85::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
